/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./components/SideNav.vue')['default']
    SideNavItem: typeof import('./components/SideNavItem.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
