/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    Block: typeof import('./components/Block.vue')['default']
    Blurry: typeof import('./components/Blurry.vue')['default']
    Btn: typeof import('./components/Btn.vue')['default']
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Group: typeof import('./components/Group.vue')['default']
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    HNav: typeof import('./components/HNav.vue')['default']
    HorizontalNav: typeof import('./components/HorizontalNav.vue')['default']
    List: typeof import('./components/List.vue')['default']
    NavBtn: typeof import('./components/NavBtn.vue')['default']
    NavButton: typeof import('./components/NavButton.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    Pop: typeof import('./components/Pop.vue')['default']
    RingBox: typeof import('./components/RingBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./components/SideNav.vue')['default']
    SideNavItem: typeof import('./components/SideNavItem.vue')['default']
    Tag: typeof import('./components/Tag.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    VNav: typeof import('./components/VNav.vue')['default']
  }
}
